
package View;

import metier.NumberCellRenderer;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import interBD.AjoutBD;
import interBD.ModificationBD;
import java.net.URISyntaxException;
import javax.swing.table.DefaultTableModel;
import metier.AppelJavadoc;
import metier.TableTousModel;


/**
 * Ouvre la fenêtre de gestion des représentants. Ajout, Modification, Suppression et consultation de la liste des représentants existants.
 * @author Sandrine Ociepka
 * @author Stephane Coulon
 * @version 1.0
 */
public class RepresentantView extends javax.swing.JDialog {

   /**
    * Création de la fenêtre de gestion des représentants, chargement des données dans le tableau
     *@param parent : fenetrePrincipaleFrame
     * @param modal true ou false
     * @throws java.io.IOException erreur si le fichier parent n'existe pas
     */
    
    public RepresentantView(Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        initialise () ;
        
        // code de changement d'icone de fenêtre qui a marché mais ne semble plus marcher
        // BufferedImage img = ImageIO.read(AddRep.class.getResource("/com/san/form/logo.png"));
        // setIconImage(img);
        /**
        * Commande pour centrer la fenêtre dans l'écran
        */
       setLocationRelativeTo(null);
      
    }
        
  /**
        * changer l'icone de la fenêtre
        */   
private void initialise(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logo.png")));
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbNom = new javax.swing.JLabel();
        chpNom = new javax.swing.JTextField();
        lbPrenom = new javax.swing.JLabel();
        chpPrenom = new javax.swing.JTextField();
        chpSalaire = new javax.swing.JTextField();
        lbSalaire = new javax.swing.JLabel();
        chpTxCommission = new javax.swing.JTextField();
        lbTxCommission = new javax.swing.JLabel();
        Titre = new javax.swing.JLabel();
        bAjouter = new javax.swing.JButton();
        bSupprimer = new javax.swing.JButton();
        bEffacer = new javax.swing.JButton();
        bModifier = new javax.swing.JButton();
        lbIdentifiant = new javax.swing.JLabel();
        lbid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel model = new DefaultTableModel();
        tablerep = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mRetour = new javax.swing.JMenu();
        mAide = new javax.swing.JMenu();
        maproposde = new javax.swing.JMenuItem();
        mjavadoc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ToutBois - Gestion Représentants");
        setAutoRequestFocus(false);

        jPanel1.setBackground(new java.awt.Color(187, 235, 219));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(191, 191, 179));

        lbNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNom.setText("Nom *");

        chpNom.setColumns(10);
        chpNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpNomActionPerformed(evt);
            }
        });

        lbPrenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPrenom.setText("Prénom *");

        chpPrenom.setColumns(10);
        chpPrenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpPrenomActionPerformed(evt);
            }
        });

        chpSalaire.setColumns(10);
        chpSalaire.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpSalaireActionPerformed(evt);
            }
        });

        lbSalaire.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSalaire.setText("Salaire brut *");

        chpTxCommission.setColumns(10);
        chpTxCommission.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chpTxCommission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chpTxCommissionActionPerformed(evt);
            }
        });

        lbTxCommission.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTxCommission.setText("Taux de commission *");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSalaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chpSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrenom)
                                    .addComponent(lbNom))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chpNom, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(chpPrenom)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTxCommission)
                                .addGap(18, 18, 18)
                                .addComponent(chpTxCommission, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(1129, 1129, 1129))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chpNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrenom)
                    .addComponent(chpPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chpSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSalaire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chpTxCommission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTxCommission))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(210, 70, 290, 150);

        Titre.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        Titre.setText("Gestion des représentants");
        jPanel1.add(Titre);
        Titre.setBounds(30, 20, 500, 30);

        bAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconeplus.jpg"))); // NOI18N
        bAjouter.setText("Ajouter");
        bAjouter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAjouterMouseClicked(evt);
            }
        });
        bAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAjouterActionPerformed(evt);
            }
        });
        jPanel1.add(bAjouter);
        bAjouter.setBounds(570, 100, 120, 27);

        bSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconemoins.jpg"))); // NOI18N
        bSupprimer.setText("Supprimer");
        bSupprimer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSupprimerMouseClicked(evt);
            }
        });
        bSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSupprimerActionPerformed(evt);
            }
        });
        jPanel1.add(bSupprimer);
        bSupprimer.setBounds(570, 160, 120, 27);

        bEffacer.setText("Effacer");
        bEffacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEffacerMouseClicked(evt);
            }
        });
        bEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEffacerActionPerformed(evt);
            }
        });
        jPanel1.add(bEffacer);
        bEffacer.setBounds(570, 190, 120, 23);

        bModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconemodif.jpg"))); // NOI18N
        bModifier.setText("Modifier");
        bModifier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bModifierMouseClicked(evt);
            }
        });
        bModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModifierActionPerformed(evt);
            }
        });
        jPanel1.add(bModifier);
        bModifier.setBounds(570, 130, 120, 27);

        lbIdentifiant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbIdentifiant.setText("Identifiant");
        jPanel1.add(lbIdentifiant);
        lbIdentifiant.setBounds(10, 80, 60, 20);
        jPanel1.add(lbid);
        lbid.setBounds(80, 80, 40, 20);

        tablerep.setDefaultRenderer(Object.class, new NumberCellRenderer());
        TableTousModel.TableRepModel(model);
        tablerep.setModel(model);
        tablerep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablerepMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablerep);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(32, 230, 700, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/meubles4.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 380);

        mRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconearbre.jpg"))); // NOI18N
        mRetour.setText("Retour à la fenêtre principale");
        mRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRetourMouseClicked(evt);
            }
        });
        mRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRetourActionPerformed(evt);
            }
        });
        jMenuBar1.add(mRetour);

        mAide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconeaide.jpg"))); // NOI18N
        mAide.setText("Aide");

        maproposde.setText("A propos de");
        maproposde.setToolTipText("");
        maproposde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maproposdeActionPerformed(evt);
            }
        });
        mAide.add(maproposde);

        mjavadoc.setText("Javadoc");
        mjavadoc.setToolTipText("");
        mjavadoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mjavadocActionPerformed(evt);
            }
        });
        mAide.add(mjavadoc);

        jMenuBar1.add(mAide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chpPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpPrenomActionPerformed

         
    }//GEN-LAST:event_chpPrenomActionPerformed

    private void chpNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpNomActionPerformed
         
    }//GEN-LAST:event_chpNomActionPerformed

    private void chpTxCommissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpTxCommissionActionPerformed
        
    }//GEN-LAST:event_chpTxCommissionActionPerformed

    private void chpSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chpSalaireActionPerformed
       
    }//GEN-LAST:event_chpSalaireActionPerformed

    private void mRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRetourMouseClicked
         dispose();
    }//GEN-LAST:event_mRetourMouseClicked

    private void bEffacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEffacerMouseClicked
       
    }//GEN-LAST:event_bEffacerMouseClicked

    private void bModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModifierActionPerformed
      String repid = lbid.getText() ;
        int repid1 = Integer.parseInt(repid);
        String repnom = chpNom.getText() ;
        String repprenom = chpPrenom.getText() ;
        String sal = chpSalaire.getText () ;
        float sal1 = Float.parseFloat(sal);
        String txc = chpTxCommission.getText() ;
        float txc1 = Float.parseFloat(txc);
        String repActif = "oui" ;
        
        ModificationBD.modRep(repActif,repid1,repnom,repprenom,sal1,txc1);
        
            // Actualisation de la table
           DefaultTableModel model = new DefaultTableModel();
            TableTousModel.TableRepModel(model);
            tablerep.setModel(model);

            // Effacer les données du formulaire
            chpNom.setText ("") ;
            chpPrenom.setText ("") ;
            chpSalaire.setText ("") ;
            chpTxCommission.setText ("") ;
            lbid.setText ("") ;
          
    }//GEN-LAST:event_bModifierActionPerformed

    private void bSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSupprimerMouseClicked
       
    }//GEN-LAST:event_bSupprimerMouseClicked

    private void bModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModifierMouseClicked
        
    }//GEN-LAST:event_bModifierMouseClicked

    private void bAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAjouterMouseClicked
   
    }//GEN-LAST:event_bAjouterMouseClicked

    private void maproposdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maproposdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maproposdeActionPerformed

    private void mjavadocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjavadocActionPerformed
      try {
            AppelJavadoc.lancerjavadoc ();
        } catch (URISyntaxException ex) {
            Logger.getLogger(FenetrePrincipaleFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mjavadocActionPerformed

    private void tablerepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablerepMouseClicked
    // Je récupére l'identifiant, colonne 1.
    String idrepval = String.valueOf(tablerep.getModel().getValueAt(tablerep.getSelectedRow(),0));
        lbid.setText (idrepval);
        // Je récupére le nom, colonne 2.
        chpNom.setText ((String) tablerep.getModel().getValueAt(tablerep.getSelectedRow(),1));
        // Je récupére le Prenom, colonne 3.
        chpPrenom.setText ((String) tablerep.getModel().getValueAt(tablerep.getSelectedRow(),2));
        // Je récupére le salaire, colonne 4.
        String salval = String.valueOf(tablerep.getModel().getValueAt(tablerep.getSelectedRow(),3));
        chpSalaire.setText (salval);
        // Je récupére le taux de commission, colonne 5.
        String txcval = String.valueOf(tablerep.getModel().getValueAt(tablerep.getSelectedRow(),4));
        chpTxCommission.setText (txcval);
        
    }//GEN-LAST:event_tablerepMouseClicked

    private void mRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRetourActionPerformed
        dispose();
    }//GEN-LAST:event_mRetourActionPerformed

    private void bAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAjouterActionPerformed
         // récupération des données du formulaire
        String repnom = chpNom.getText() ;
        String repprenom = chpPrenom.getText() ;
        String repSalaire = chpSalaire.getText () ; 
        int repsal = Integer.parseInt(repSalaire);
        String repTxtCommission = chpTxCommission.getText() ;
        float txc = Float.parseFloat(repTxtCommission);
        String repActif = "oui" ;
        
         AjoutBD.addRep(repActif,repnom,repprenom,repsal,txc);
       
          // Actualisation de la table
           DefaultTableModel model = new DefaultTableModel();
            TableTousModel.TableRepModel(model);
            tablerep.setModel(model);
  
   // Effacer les données du formulaire
            chpNom.setText ("") ;
            chpPrenom.setText ("") ;
            chpSalaire.setText ("") ;
            chpTxCommission.setText ("") ;
    }//GEN-LAST:event_bAjouterActionPerformed

    private void bSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSupprimerActionPerformed

        String repActif = "non" ;
        String repid = lbid.getText() ;
        int repid1 = Integer.parseInt(repid);
        String repnom = chpNom.getText() ;
        String repprenom = chpPrenom.getText() ;
        String sal = chpSalaire.getText () ;
        float sal1 = Float.parseFloat(sal);
        String txc = chpTxCommission.getText() ;
        float txc1 = Float.parseFloat(txc);

       ModificationBD.modRep(repActif,repid1,repnom,repprenom,sal1,txc1);
           
              // Actualisation de la table
           DefaultTableModel model = new DefaultTableModel();
            TableTousModel.TableRepModel(model);
            tablerep.setModel(model);

            // Effacer les données du formulaire
            chpNom.setText ("") ;
            chpPrenom.setText ("") ;
            chpSalaire.setText ("") ;
            chpTxCommission.setText ("") ;
            lbid.setText ("") ;
        
    }//GEN-LAST:event_bSupprimerActionPerformed

    private void bEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEffacerActionPerformed
         // Action sur le bouton Effacer, purge des champs de saisies et suppression de la selection dans la table.
        chpNom.setText ("") ;
        chpPrenom.setText ("") ;
        chpSalaire.setText ("") ;
        chpTxCommission.setText ("") ;
        lbid.setText ("") ;
        tablerep.getSelectionModel().clearSelection();
        
    }//GEN-LAST:event_bEffacerActionPerformed

    /**
     * Mise en page de la fenêtre de gestion de représentants
     * @param args arguments utilisés pour créer la fenêtre
     */
    public static void FenetreRepresentant (String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RepresentantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RepresentantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RepresentantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RepresentantView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RepresentantView dialog = null;
                try {
                    dialog = new RepresentantView(new javax.swing.JFrame(), true);
                } catch (IOException ex) {
                    Logger.getLogger(RepresentantView.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titre;
    private javax.swing.JButton bAjouter;
    private javax.swing.JButton bEffacer;
    private javax.swing.JButton bModifier;
    private javax.swing.JButton bSupprimer;
    private javax.swing.JTextField chpNom;
    private javax.swing.JTextField chpPrenom;
    private javax.swing.JTextField chpSalaire;
    private javax.swing.JTextField chpTxCommission;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIdentifiant;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbPrenom;
    private javax.swing.JLabel lbSalaire;
    private javax.swing.JLabel lbTxCommission;
    private javax.swing.JLabel lbid;
    private javax.swing.JMenu mAide;
    private javax.swing.JMenu mRetour;
    private javax.swing.JMenuItem maproposde;
    private javax.swing.JMenuItem mjavadoc;
    private javax.swing.JTable tablerep;
    // End of variables declaration//GEN-END:variables
}
